// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gkmsvm_classify
void gkmsvm_classify(SEXP params);
RcppExport SEXP gkmSVM_gkmsvm_classify(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type params(paramsSEXP);
    gkmsvm_classify(params);
    return R_NilValue;
END_RCPP
}
// gkmsvm_kernel
void gkmsvm_kernel(SEXP params);
RcppExport SEXP gkmSVM_gkmsvm_kernel(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type params(paramsSEXP);
    gkmsvm_kernel(params);
    return R_NilValue;
END_RCPP
}
