// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gkm_classify_cpp
void gkm_classify_cpp(SEXP params);
RcppExport SEXP _gkmSVM_gkm_classify_cpp(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type params(paramsSEXP);
    gkm_classify_cpp(params);
    return R_NilValue;
END_RCPP
}
// gkm_crc32_cpp
int gkm_crc32_cpp(Rcpp::RawVector x);
RcppExport SEXP _gkmSVM_gkm_crc32_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(gkm_crc32_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// gkm_kernel_cpp
void gkm_kernel_cpp(SEXP params);
RcppExport SEXP _gkmSVM_gkm_kernel_cpp(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type params(paramsSEXP);
    gkm_kernel_cpp(params);
    return R_NilValue;
END_RCPP
}
// gkm_train_cpp
void gkm_train_cpp(SEXP params);
RcppExport SEXP _gkmSVM_gkm_train_cpp(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type params(paramsSEXP);
    gkm_train_cpp(params);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gkmSVM_gkm_classify_cpp", (DL_FUNC) &_gkmSVM_gkm_classify_cpp, 1},
    {"_gkmSVM_gkm_crc32_cpp", (DL_FUNC) &_gkmSVM_gkm_crc32_cpp, 1},
    {"_gkmSVM_gkm_kernel_cpp", (DL_FUNC) &_gkmSVM_gkm_kernel_cpp, 1},
    {"_gkmSVM_gkm_train_cpp", (DL_FUNC) &_gkmSVM_gkm_train_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_gkmSVM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
