# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gkm_classify_cpp <- function(params) {
    invisible(.Call('_gkmSVM_gkm_classify_cpp', PACKAGE = 'gkmSVM', params))
}

.gkm_crc32_cpp <- function(x) {
    .Call('_gkmSVM_gkm_crc32_cpp', PACKAGE = 'gkmSVM', x)
}

.gkm_kernel_cpp <- function(params) {
    invisible(.Call('_gkmSVM_gkm_kernel_cpp', PACKAGE = 'gkmSVM', params))
}

.gkm_train_cpp <- function(params) {
    invisible(.Call('_gkmSVM_gkm_train_cpp', PACKAGE = 'gkmSVM', params))
}

